services:
  frontend:
    image: 182freak/234-deploylab-frontend:latest
    pull_policy: always
    ports:
      - "8081:8080"
    environment:
      VITE_GRAPHQL_URI: http://100.57.163.24:8082/graphql
      VITE_SERVER_URI: http://100.57.163.24:8082
    restart: unless-stopped